In [11]:
import numpy as np 
import pandas as pd 

In [15]:
X=pd.read_csv('C:/Users/My PC/Desktop/Machine Learning/Data Engineer/tree_class_feats.csv')
y=pd.read_csv('C:/Users/My PC/Desktop/Machine Learning/Data Engineer/tree_class_target.csv')

In [16]:
X.head()

feature 1  feature 2  feature 3  feature 4  feature 5  feature 6  \
0   1.722029  -4.689223  -0.207066   2.498555   2.883010   1.579690   
1   0.236202  -2.412059  -2.977042   2.837931   4.201749   0.536090   
2   0.592300  -3.678390  -0.282953   0.912839   1.055228   1.235441   
3   1.579346  -1.135482   0.734795  -3.840698  -0.362227   2.641352   
4  -2.962439   1.754583  -1.145055   1.857364   0.989132   2.567482   

   feature 7  feature 8  feature 9  feature 10  
0  -2.720014  -1.246192   1.168185    1.400007  
1   0.266874  -1.308043   3.728172   -1.198629  
2  -3.378884  -1.117221  -0.274793    0.098392  
3  -3.080336  -1.728918  -2.738785   -1.061155  
4   2.058646  -7.009674  -2.108419    1.437935

In [39]:
y.head(10)

Class
0      0
1      1
2      0
3      1
4      1
5      0
6      0
7      0
8      0
9      1

In [19]:
np.unique(y)

array([0, 1], dtype=int64)

In [21]:
from keras.models import Sequential
from tensorflow import random
np.random.seed(42)
random.set_seed(42)
model=Sequential()

In [24]:
from keras.layers import Dense,Activation
model.add(Dense(10, activation='tanh', input_dim=10))

In [25]:
model.add(Dense(5,activation='tanh'))

In [26]:
model.add(Dense(1,activation='sigmoid'))

In [27]:
model.compile(optimizer='SGD',loss='binary_crossentropy')

In [28]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 6         
Total params: 281
Trainable params: 281
Non-trainable params: 0
_________________________________________________________________


In [34]:
history=model.fit(X,y,epochs=100,batch_size=5,verbose=1,validation_split=0.2,shuffle=False)

Train on 8000 samples, validate on 2000 samples
Epoch 1/100
8000/8000 [==============================] - 7s 815us/step - loss: 0.1332 - val_loss: 0.1430
Epoch 2/100
8000/8000 [==============================] - 4s 479us/step - loss: 0.1330 - val_loss: 0.1428
Epoch 3/100
8000/8000 [==============================] - 4s 440us/step - loss: 0.1329 - val_loss: 0.1426
Epoch 4/100
8000/8000 [==============================] - 4s 443us/step - loss: 0.1327 - val_loss: 0.1423
Epoch 5/100
8000/8000 [==============================] - 4s 476us/step - loss: 0.1325 - val_loss: 0.1421
Epoch 6/100
8000/8000 [==============================] - 4s 476us/step - loss: 0.1324 - val_loss: 0.1418
Epoch 7/100
8000/8000 [==============================] - 3s 396us/step - loss: 0.1322 - val_loss: 0.1416
Epoch 8/100
8000/8000 [==============================] - 3s 391us/step - loss: 0.1321 - val_loss: 0.1414
Epoch 9/100
8000/8000 [==============================] - 3s 410us/step - loss: 0.1320 - val_loss: 0.1412
Epoch 1

Epoch 78/100
8000/8000 [==============================] - 3s 380us/step - loss: 0.1257 - val_loss: 0.1413
Epoch 79/100
8000/8000 [==============================] - 3s 429us/step - loss: 0.1256 - val_loss: 0.1414
Epoch 80/100
8000/8000 [==============================] - 3s 384us/step - loss: 0.1256 - val_loss: 0.1415
Epoch 81/100
8000/8000 [==============================] - 3s 388us/step - loss: 0.1255 - val_loss: 0.1415
Epoch 82/100
8000/8000 [==============================] - 3s 418us/step - loss: 0.1254 - val_loss: 0.1416
Epoch 83/100
8000/8000 [==============================] - 3s 389us/step - loss: 0.1254 - val_loss: 0.1416
Epoch 84/100
8000/8000 [==============================] - 3s 379us/step - loss: 0.1253 - val_loss: 0.1417
Epoch 85/100
8000/8000 [==============================] - 3s 385us/step - loss: 0.1253 - val_loss: 0.1417
Epoch 86/100
8000/8000 [==============================] - 3s 383us/step - loss: 0.1252 - val_loss: 0.1418
Epoch 87/100
8000/8000 [======================

In [36]:
import matplotlib.pyplot as plt
%matplotlib inlineimport matplotlib.pyplot as plt
%matplotlib inline
# Plot training & validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()
# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()
# Plot training & validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()
# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

UsageError: unrecognized arguments: matplotlib.pyplot as plt


In [37]:
y_predicted = model.predict(X.iloc[0:10,:])

In [38]:
 # print the predicted classes
print("Predicted probability for each of the examples belonging to class 1: "),
print(y_predicted)
print("Predicted class label for each of the examples: "), 
print(np.round(y_predicted))

Predicted probability for each of the examples belonging to class 1: 
[[0.00468563]
 [0.38649455]
 [0.00481594]
 [0.96284145]
 [0.99802715]
 [0.00301919]
 [0.39244363]
 [0.00263148]
 [0.00916286]
 [0.99682826]]
Predicted class label for each of the examples: 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
